#!/usr/bin/env node
'use strict';
// Regenerates the gateway's price table from the CLI catalog.
//
// The gateway (Python) and `peek` (Node) both have to price the same call the same
// way — the gateway's numbers are reported to the user WITHOUT a "~", so a divergence
// between the two shows up as an authoritative-looking wrong figure. Hand-maintaining
// two copies is what let them drift a full model generation apart, so the JS catalog
// in src/peek/models.js is now the single source of truth and this script mechanically
// projects it into cli/assets/gateway/app/model_prices.json (the one gateway copy).
//
//   node scripts/sync-prices.js          write the gateway table
//   node scripts/sync-prices.js --check  exit 1 if it is stale (CI / test guard)

// There used to be two gateway copies (a dev tree + the npm-shipped cli/assets/gateway)
// kept in step by hand, so a fix to one never reached users. They are now ONE directory
// (cli/assets/gateway; the top-level gateway/ is a symlink to it), so this script only
// (re)generates the price table and checks cross-runtime JS/Python parity.

const fs = require('fs');
const path = require('path');
const { CATALOG, CATALOG_AS_OF, resolveModel } = require('../src/peek/models');
const { REPRESENTATIVE, ROUTE_TARGET_BY_TIER } = require('../src/peek/pricing');

const REPO = path.resolve(__dirname, '../..');
// One gateway copy now: cli/assets/gateway is the single source npm ships, and the
// top-level `gateway/` is a symlink to it (kept so Docker builds, docs, and
// `pytest gateway/tests` keep resolving). No dev/shipped split left to drift.
const GATEWAY = path.join(REPO, 'cli/assets/gateway/app');

function priceTable() {
  return JSON.stringify({
    _comment: 'GENERATED by cli/scripts/sync-prices.js from cli/src/peek/models.js. '
      + 'Do not edit by hand — edit the JS catalog and re-run the script.',
    as_of: CATALOG_AS_OF,
    representative: REPRESENTATIVE,
    // ROUTING TARGETS, keyed family -> tier -> model id, tier names being the same
    // haiku/sonnet/opus the gateway already speaks. `representative` above is the same
    // table keyed by PRICE BUCKET (cheap/mid/top) and is what pricing.py already reads;
    // this second view exists so router.py / app.py can stop hardcoding a THIRD and
    // FOURTH copy of "which model does tier X mean". See the long note on
    // ROUTE_TARGET_BY_TIER in src/peek/pricing.js for the measured divergence this
    // closes (11 overstating + 26 understating family/tier pairs on 2026-08-08).
    route_targets: ROUTE_TARGET_BY_TIER,
    models: CATALOG,
  }, null, 2) + '\n';
}

// [label, destination path, contents] — every artifact that must agree.
//
// The .py mirror list is DERIVED from gateway/app rather than hand-listed. A hardcoded
// list silently stops covering a file the moment someone adds one, which is the same
// failure mode as a hand-maintained price table: it looks maintained right up until it
// isn't.
const table = priceTable();
// A single generated artifact now — the one gateway copy's price table, projected
// from the JS catalog. (The Python modules live in that same dir and are edited in
// place; there is no second copy to mirror them into anymore.)
const targets = [
  ['cli/assets/gateway/app/model_prices.json', path.join(GATEWAY, 'model_prices.json'), table],
];

const check = process.argv.includes('--check');
let stale = 0;
for (const [label, dest, next] of targets) {
  const prev = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : null;
  if (prev === next) continue;
  if (check) { console.error('STALE: ' + label); stale++; continue; }
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, next);
  console.log('wrote ' + label);
}

// ---- route targets must NAME REAL MODELS ----------------------------------------
// ROUTE_TARGET is now the one place that answers "which model does tier X mean", for
// both runtimes. That makes a typo in it a silent, product-wide mis-price rather than a
// local one: representativeFor() would hand back a string, resolveModel() would return
// null, and costOfDetailed() would price the counterfactual at $0 — a downgrade that
// appears to be free. Checked here, at the moment the table is projected outward.
//
// The target must also BE of the tier it is sold as. A model one tier BELOW its slot is
// how the gateway's OpenAI front end came to answer auto-escalated security/concurrency
// requests on `o3` — which this catalog classifies as tier `sonnet` — while reporting
// them as top tier. A model ABOVE its slot is the same defect pointed the other way: the
// caller asked for the cheap tier and is billed for a flagship.
//
// ONE exception is legitimate: a family that publishes no model of that tier at all.
// DeepSeek ships exactly two SKUs (flash = haiku, pro = opus), so its `sonnet` slot has
// nothing of its own to name and correctly falls back DOWN to flash. Falling back UP is
// never allowed, because that spends the user's money to fill a gap they did not ask to
// have filled.
const { TIERS, rank } = require('../src/peek/classify');

// KNOWN, ENUMERATED mismatches that cannot be corrected from this file alone. This is a
// RATCHET, not an excuse: a mismatch that is not listed here fails the gate, and a listed
// one that no longer reproduces ALSO fails the gate, so the list cannot outlive its
// blockers. Every entry names the exact blocker and the exact fix.
const KNOWN_TIER_MISMATCHES = {
  'mistral.sonnet':
    "target 'mistral-small-4' is tier haiku, so Mistral's mid slot is filled by a cheap "
    + "model and a sonnet-tier request is silently answered one tier down. Fix: point it "
    + "at 'mistral-medium-3.5' (tier sonnet). BLOCKED BY cli/test/peek.test.js:343, whose "
    + "`mid <= top` price invariant this correction would break — mistral-medium-3.5 "
    + "prices at $9.00/2Mtok while the corrected top target prices at $2.00.",
  'mistral.opus':
    "target 'mistral-medium-3.5' is tier sonnet, so an auto-escalated hard request on a "
    + "Mistral model is answered by a MID-capability model while reported as top tier. "
    + "Fix: point it at 'mistral-large-3' (tier opus) — which is also CHEAPER "
    + "($0.5/$1.5 vs $1.5/$7.5), so this correction raises quality and lowers cost. "
    + "BLOCKED BY the same cli/test/peek.test.js:343 `mid <= top` invariant, which the "
    + "catalog itself already contradicts (models.js:64: 'Mistral's flagship costs less "
    + "than its mid model').",
};

let targetFailures = 0;
const seenMismatches = new Set();
for (const famName of Object.keys(ROUTE_TARGET_BY_TIER)) {
  const tiers = ROUTE_TARGET_BY_TIER[famName];
  // Which tiers this family actually publishes, so a legitimate gap is distinguishable
  // from a careless slot.
  const published = new Set(CATALOG.filter((e) => e.family === famName).map((e) => e.tier));
  for (const tierName of TIERS) {
    const key = famName + '.' + tierName;
    const id = tiers[tierName];
    if (!id) {
      console.error(`ROUTE TARGET MISSING: ${key} is empty`);
      targetFailures++;
      continue;
    }
    const entry = resolveModel(id);
    if (!entry) {
      console.error(`ROUTE TARGET UNPRICEABLE: ${key} -> '${id}'`
        + ' resolves to no catalog entry');
      targetFailures++;
      continue;
    }
    if (entry.tier === tierName) continue;
    if (rank(entry.tier) < rank(tierName) && !published.has(tierName)) {
      // Legitimate gap: the family publishes nothing of this tier, so the slot falls
      // back DOWN to the nearest thing it does publish.
      continue;
    }
    seenMismatches.add(key);
    const known = KNOWN_TIER_MISMATCHES[key];
    const line = `ROUTE TARGET TIER MISMATCH: ${key} -> '${id}' is catalogued as tier`
      + ` '${entry.tier}'`;
    if (known) {
      console.error(line + '\n  KNOWN (ratcheted): ' + known);
    } else {
      console.error(line);
      targetFailures++;
    }
  }
}
// A ledger entry that no longer reproduces is a lie about the current state — fail on it
// so the list shrinks as the blockers are cleared.
for (const key of Object.keys(KNOWN_TIER_MISMATCHES)) {
  if (!seenMismatches.has(key)) {
    console.error(`ROUTE TARGET LEDGER STALE: ${key} is listed in KNOWN_TIER_MISMATCHES`
      + ' but no longer mismatches — delete the entry');
    targetFailures++;
  }
}
if (!targetFailures) {
  const n = Object.keys(ROUTE_TARGET_BY_TIER).length * TIERS.length;
  console.log('route targets: ' + n + ' entries resolve; '
    + seenMismatches.size + ' known tier mismatch(es) ratcheted');
}

// ---- cross-runtime parity -------------------------------------------------------
// Byte-identical mirrors are not enough: the two runtimes carry hand-written ports of
// the same logic, and those can disagree while every file is "in sync". They already
// did — `magistral-*` and `devstral-*` resolved to the mistral family in JS and to
// nothing in Python, so the gateway silently reported $0 saved for those users on the
// path that prints no "about" qualifier.
//
// So: ask BOTH runtimes to price the same probes and require identical answers.
function parityProbes() {
  const ids = CATALOG.map((e) => e.id);
  // Plus ids that must resolve to nothing, so a fail-open regression is caught too.
  return ids.concat(['claude-opus-4-9', 'gpt-5.6', 'o3-deep-research', 'llama-4-maverick',
    'totally-made-up', 'us.anthropic.claude-opus-5', 'claude-opus-5-20260101']);
}

function jsAnswers(ids, at) {
  const { detectFamily, isPriceable, costOfModel } = require('../src/peek/pricing');
  const out = {};
  for (const id of ids) {
    out[id] = {
      family: detectFamily(id) || null,
      priceable: !!isPriceable(id),
      cost: costOfModel(id, { inFresh: 1e6, outTok: 1e6 }, { at }),
    };
  }
  return out;
}

function pyAnswers(ids, at) {
  const { execFileSync } = require('child_process');
  const script = [
    'import json,sys',
    'sys.path.insert(0, ' + JSON.stringify(GATEWAY) + ')',
    'sys.path.insert(0, ' + JSON.stringify(path.dirname(GATEWAY)) + ')',
    'from pricing import detect_family, is_priceable, cost_of_model',
    'ids=json.loads(sys.stdin.read()); at=' + JSON.stringify(at),
    'out={}',
    'for i in ids:',
    '    out[i]={"family":detect_family(i),"priceable":bool(is_priceable(i)),'
      + '"cost":cost_of_model(i,1e6,1e6,at=at)}',
    'print(json.dumps(out))',
  ].join('\n');
  const raw = execFileSync('python3', ['-c', script], {
    input: JSON.stringify(ids), encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'],
  });
  return JSON.parse(raw);
}

let parityFailures = 0;
try {
  const ids = parityProbes();
  const at = CATALOG_AS_OF; // fixed date so the comparison is deterministic
  const js = jsAnswers(ids, at);
  const py = pyAnswers(ids, at);
  const near = (a, b) => (a == null || b == null) ? a === b : Math.abs(a - b) < 1e-9;
  for (const id of ids) {
    const a = js[id], b = py[id];
    if (!b) { console.error('PARITY: python returned nothing for ' + id); parityFailures++; continue; }
    if (a.family !== b.family || a.priceable !== b.priceable || !near(a.cost, b.cost)) {
      console.error('PARITY MISMATCH ' + id
        + '\n  js:     ' + JSON.stringify(a)
        + '\n  python: ' + JSON.stringify(b));
      parityFailures++;
    }
  }
  if (!parityFailures) console.log('cross-runtime parity: ' + ids.length + ' ids agree');
} catch (e) {
  // A missing python3 must not silently pass the guard in CI.
  console.error('PARITY CHECK COULD NOT RUN: ' + (e && e.message));
  parityFailures++;
}

if (stale || parityFailures || targetFailures) {
  if (stale) console.error('\n' + stale + ' file(s) stale — run: node cli/scripts/sync-prices.js');
  if (parityFailures) console.error(parityFailures + ' cross-runtime parity failure(s)');
  if (targetFailures) console.error(targetFailures + ' route-target failure(s)');
  process.exit(1);
}
console.log(check ? 'price tables are in sync' : 'done');
